version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - vimov
    volumes:
      - incognitus_db:/var/lib/mysql
      - incognitus_config:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ouq8Vba6UFwuK4jW3z
      MYSQL_DATABASE: incognitus
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3

  minio:
    image: quay.io/minio/minio
    container_name: minio
    networks:
      - vimov
      - proxy
    volumes:
      - incognitus_data:/data
    environment:
      MINIO_ACCESS_KEY: Ek3aIA2MpWOqW0Z56Yee
      MINIO_SECRET_KEY: D9NdhLcC8VwFnQiOU0zTF4oYHRolf8no8sszhDP3
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 06DmX*_6RQj¡c^->lb/7
      END_BUCKET: incognitus_end
      RAW_BUCKET: incognitus_raw
    command: server /data --console-address ":9090"
    deploy:
      replicas: 1
      labels:
        com.df.distribute: "true"
        com.df.notify: "true"
        com.df.port: 9000
        com.df.servicePath: "/incognitusminio"

  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
      - incognitus
    networks:
      - vimov
    environment:
      MINIO_ACCESS_KEY: Ek3aIA2MpWOqW0Z56Yee
      MINIO_SECRET_KEY: D9NdhLcC8VwFnQiOU0zTF4oYHRolf8no8sszhDP3
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 06DmX*_6RQj¡c^->lb/7
      END_BUCKET: incognitus_end
      RAW_BUCKET: incognitus_raw
    volumes:
      - incognitus_config:/config_files
    entrypoint:
      - /config_files/minio_init.sh

  incognitus:
    restart: always
    image: i2thub.icesi.edu.co:5000/incognitus:latest
    networks:
      - vimov
      - proxy
    depends_on:
      - mysql
    deploy:
      replicas: 1
      labels:
        com.df.distribute: "true"
        com.df.notify: "true"
        com.df.port: 5000
        com.df.servicePath: "/incognitus"

  moca:
    restart: always
    image: i2thub.icesi.edu.co:5000/moca:latest
    networks:
      - vimov
      - proxy
    depends_on:
      - mysql
    deploy:
      replicas: 1
      labels:
        com.df.distribute: "true"
        com.df.notify: "true"
        com.df.port: 4020
        com.df.servicePath: "/moca"

volumes:
  incognitus_data:
    external: true
  incognitus_db:
    external: true
  incognitus_config:
    external: true

networks:
  vimov:
  proxy:
    external: true
